"""item-model-seeders

Revision ID: 5c79a794a9b7
Revises: ffdc0a98111c
Create Date: 2023-06-14 11:00:07.720958

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '5c79a794a9b7'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lastKnownPriceCents', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('users', sa.Column('cashCents', sa.Integer(), nullable=True))

    #???
    # op.add_column('users', sa.Column('firstname', sa.String(length=50), nullable=False))
    # op.add_column('users', sa.Column('lastname', sa.String(length=50), nullable=False))



    # ### end Alembic commands ###

    if environment == "production":
        op.execute(f"ALTER TABLE items SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'cashCents')
    # op.drop_column('users', 'firstname')
    # op.drop_column('users', 'lastname')
    op.drop_table('items')
    # ### end Alembic commands ###
