"""auctions-and-bids

Revision ID: 1c018820b5c7
Revises: 5c79a794a9b7
Create Date: 2023-06-18 14:09:05.936189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c018820b5c7'
down_revision = '5c79a794a9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auctionName', sa.Text(), nullable=False),
    sa.Column('auctionDescription', sa.Text(), nullable=True),
    sa.Column('auctionOpen', sa.Boolean(), nullable=True),
    sa.Column('startingBidCents', sa.Integer(), nullable=False),
    sa.Column('finalBidCents', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('auctionItemId', sa.Integer(), nullable=True),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auctionItemId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auctionId', sa.Integer(), nullable=True),
    sa.Column('bidderId', sa.Integer(), nullable=True),
    sa.Column('timeOfBid', sa.DateTime(), nullable=False),
    sa.Column('bidAmountCents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auctionId'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('auctions')
    # ### end Alembic commands ###